import streamlit as st

def render_intro(col=None):
    target = col if col is not None else st

    target.markdown(
        """
        ### Revealing hidden bias in job ads
        It’s easy to overlook the subtle ways word choices in job advertisements can shape who feels welcome or excluded. Phrases like “culture fit” or “native English speaker” may seem friendly or professional, but they can quietly reinforce old barriers and discourage qualified applicants.

        Whether written by a human or generated by an AI tool, job ads often contain language that signals gender, age, personality or background preferences in ways that aren’t always obvious. Research shows these hidden patterns persist across industries, limiting opportunity and fairness even in polished, well-intentioned postings.

        This tool helps you quickly identify and understand the risks hidden in job description text. By highlighting risky language and explaining why it matters, we aim to make fairness, trust, and inclusion part of every hiring conversation.

        Paste your job ad and discover how small changes in wording can open up opportunity for everyone.
        """
    )